# Generated by Django 2.1.7 on 2019-04-01 08:29

import Catalog.media_paths
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True, verbose_name='Название категории')),
                ('Keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='слова и словосочетания, описывающие категорию', size=None, verbose_name='Ключевые слова')),
                ('TranslitTitle', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('TranslitTitle', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы категорий',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Без навзания', max_length=100, unique=True, verbose_name='Название')),
                ('UrlHash', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('Characteristics', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Характеристики товара')),
                ('Price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('Description', models.TextField(null=True, verbose_name='Описание')),
                ('Main_image', models.ImageField(help_text='Эта фотография будет отображаться в карточке товара', null=True, upload_to=Catalog.media_paths.generate_path, verbose_name='Главная фотография товара')),
                ('Images', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(blank=True, null=True, upload_to=Catalog.media_paths.generate_path), size=None, verbose_name='Галерея')),
                ('Units', models.CharField(max_length=50, verbose_name='Ед. изм. товара')),
                ('Page_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), help_text='Cлова и словосочетания описывающие содержимое страницы(Необходимо для SEO оптимизации)', null=True, size=None)),
                ('Page_description', models.CharField(help_text='Текст для <meta description>(Необходимо для SEO оптимизации)', max_length=200, null=True, verbose_name='Описание страницы')),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='Catalog.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='GoodAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('Type', models.CharField(choices=[('str', 'Текстовая'), ('float', 'Число с запятой'), ('int', 'Целое число'), ('bool', 'Да / Нет')], max_length=50, null=True, verbose_name='Тип характеристики товара')),
                ('PossibleValues', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=250), blank=True, null=True, size=None, verbose_name='Возможные значения характеристики')),
                ('Units', models.CharField(blank=True, max_length=40, null=True, verbose_name='Единицы измерения')),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='Catalog.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='Group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Catalog.CategoryGroup'),
        ),
    ]
