# Generated by Django 2.1.7 on 2019-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filtration', '0002_filter_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='Title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
